version: "3"
services:
  myurls:
    build: .
    container_name: myurls
    restart: always
    env_file: .env
    ports:
      - "${MYURLS_PORT}:${MYURLS_PORT}"
    volumes:
      - ./data/myurls/logs:/app/logs      
    entrypoint: ["/app/myurls", "-domain", "${MYURLS_DOMAIN}", "-conn", "${MYURLS_REDIS_CONN}", "-password", "${MYURLS_REDIS_PASSWORD}", "-redisDB", "${MYURLS_REDIS_DB}"]
